### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by ZeroCool22** [krazysh01/forcebindip-gui#1]
I don't see any .exe...

![Screenshot_5](https://user-images.githubusercontent.com/13344308/92190657-1b310c80-ee38-11ea-82fa-9017a9def371.png)

I also have java INSTALLED.

![Screenshot_6](https://user-images.githubusercontent.com/13344308/92190696-300da000-ee38-11ea-8b14-c83e233edb1c.png)

And ofc. ForceBindIP installed too.

Thx in advance.

**Comment by krazysh01** [comment]
This is a source code repository, you will have to build it yourself to use it from here. You can download a pre-built installer here: https://sourceforge.net/projects/forcebindip-gui/
